// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: KadDhtMessage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Libp2p.Protocols.KadDht.Messages {

  /// <summary>Holder for reflection information generated from KadDhtMessage.proto</summary>
  public static partial class KadDhtMessageReflection {

    #region Descriptor
    /// <summary>File descriptor for KadDhtMessage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static KadDhtMessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNLYWREaHRNZXNzYWdlLnByb3RvEgZkaHQucGIiOgoGUmVjb3JkEgsKA2tl",
            "eRgBIAEoDBINCgV2YWx1ZRgCIAEoDBIUCgx0aW1lUmVjZWl2ZWQYAyABKAMi",
            "xgEKB01lc3NhZ2USIQoEdHlwZRgBIAEoDjITLmRodC5wYi5NZXNzYWdlVHlw",
            "ZRILCgNrZXkYAiABKAwSHgoGcmVjb3JkGAMgASgLMg4uZGh0LnBiLlJlY29y",
            "ZBIhCgtjbG9zZXJQZWVycxgIIAMoCzIMLmRodC5wYi5QZWVyEiMKDXByb3Zp",
            "ZGVyUGVlcnMYCSADKAsyDC5kaHQucGIuUGVlchINCgV2YWx1ZRgGIAEoDBIU",
            "CgxjbHVzdGVyTGV2ZWwYByABKAUiRwoOUHJvdmlkZXJSZWNvcmQSCwoDa2V5",
            "GAEgASgMEhIKCnByb3ZpZGVySWQYAiABKAwSFAoMdGltZVJlY2VpdmVkGAMg",
            "ASgDIkkKBFBlZXISCgoCaWQYASABKAwSDQoFYWRkcnMYAiADKAwSFwoKY29u",
            "bmVjdGlvbhgDIAEoA0gAiAEBQg0KC19jb25uZWN0aW9uKmkKC01lc3NhZ2VU",
            "eXBlEg0KCVBVVF9WQUxVRRAAEg0KCUdFVF9WQUxVRRABEhAKDEFERF9QUk9W",
            "SURFUhACEhEKDUdFVF9QUk9WSURFUlMQAxINCglGSU5EX05PREUQBBIICgRQ",
            "SU5HEAVCI6oCIExpYnAycC5Qcm90b2NvbHMuS2FkRGh0Lk1lc3NhZ2VzYgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Libp2p.Protocols.KadDht.Messages.MessageType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Libp2p.Protocols.KadDht.Messages.Record), global::Libp2p.Protocols.KadDht.Messages.Record.Parser, new[]{ "Key", "Value", "TimeReceived" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Libp2p.Protocols.KadDht.Messages.Message), global::Libp2p.Protocols.KadDht.Messages.Message.Parser, new[]{ "Type", "Key", "Record", "CloserPeers", "ProviderPeers", "Value", "ClusterLevel" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Libp2p.Protocols.KadDht.Messages.ProviderRecord), global::Libp2p.Protocols.KadDht.Messages.ProviderRecord.Parser, new[]{ "Key", "ProviderId", "TimeReceived" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Libp2p.Protocols.KadDht.Messages.Peer), global::Libp2p.Protocols.KadDht.Messages.Peer.Parser, new[]{ "Id", "Addrs", "Connection" }, new[]{ "Connection" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// Message types as defined in the libp2p Kademlia DHT spec
  /// </summary>
  public enum MessageType {
    [pbr::OriginalName("PUT_VALUE")] PutValue = 0,
    [pbr::OriginalName("GET_VALUE")] GetValue = 1,
    [pbr::OriginalName("ADD_PROVIDER")] AddProvider = 2,
    [pbr::OriginalName("GET_PROVIDERS")] GetProviders = 3,
    [pbr::OriginalName("FIND_NODE")] FindNode = 4,
    [pbr::OriginalName("PING")] Ping = 5,
  }

  #endregion

  #region Messages
  /// <summary>
  /// Record represents a stored value in the DHT
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Record : pb::IMessage<Record>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Record> _parser = new pb::MessageParser<Record>(() => new Record());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Record> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Libp2p.Protocols.KadDht.Messages.KadDhtMessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Record() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Record(Record other) : this() {
      key_ = other.key_;
      value_ = other.value_;
      timeReceived_ = other.timeReceived_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Record Clone() {
      return new Record(this);
    }

    /// <summary>Field number for the "key" field.</summary>
    public const int KeyFieldNumber = 1;
    private pb::ByteString key_ = pb::ByteString.Empty;
    /// <summary>
    /// The key that references this record
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Key {
      get { return key_; }
      set {
        key_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 2;
    private pb::ByteString value_ = pb::ByteString.Empty;
    /// <summary>
    /// The actual value this record is storing
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Value {
      get { return value_; }
      set {
        value_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "timeReceived" field.</summary>
    public const int TimeReceivedFieldNumber = 3;
    private long timeReceived_;
    /// <summary>
    /// Time the record was received, Unix timestamp in seconds
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TimeReceived {
      get { return timeReceived_; }
      set {
        timeReceived_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Record);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Record other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Key != other.Key) return false;
      if (Value != other.Value) return false;
      if (TimeReceived != other.TimeReceived) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Key.Length != 0) hash ^= Key.GetHashCode();
      if (Value.Length != 0) hash ^= Value.GetHashCode();
      if (TimeReceived != 0L) hash ^= TimeReceived.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Key.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Key);
      }
      if (Value.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Value);
      }
      if (TimeReceived != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(TimeReceived);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Key.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Key);
      }
      if (Value.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Value);
      }
      if (TimeReceived != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(TimeReceived);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Key.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Key);
      }
      if (Value.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Value);
      }
      if (TimeReceived != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TimeReceived);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Record other) {
      if (other == null) {
        return;
      }
      if (other.Key.Length != 0) {
        Key = other.Key;
      }
      if (other.Value.Length != 0) {
        Value = other.Value;
      }
      if (other.TimeReceived != 0L) {
        TimeReceived = other.TimeReceived;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Key = input.ReadBytes();
            break;
          }
          case 18: {
            Value = input.ReadBytes();
            break;
          }
          case 24: {
            TimeReceived = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Key = input.ReadBytes();
            break;
          }
          case 18: {
            Value = input.ReadBytes();
            break;
          }
          case 24: {
            TimeReceived = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Message represents a Kademlia DHT protocol message
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Message : pb::IMessage<Message>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Message> _parser = new pb::MessageParser<Message>(() => new Message());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Message> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Libp2p.Protocols.KadDht.Messages.KadDhtMessageReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Message() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Message(Message other) : this() {
      type_ = other.type_;
      key_ = other.key_;
      record_ = other.record_ != null ? other.record_.Clone() : null;
      closerPeers_ = other.closerPeers_.Clone();
      providerPeers_ = other.providerPeers_.Clone();
      value_ = other.value_;
      clusterLevel_ = other.clusterLevel_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Message Clone() {
      return new Message(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Libp2p.Protocols.KadDht.Messages.MessageType type_ = global::Libp2p.Protocols.KadDht.Messages.MessageType.PutValue;
    /// <summary>
    /// Type of the message
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Libp2p.Protocols.KadDht.Messages.MessageType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "key" field.</summary>
    public const int KeyFieldNumber = 2;
    private pb::ByteString key_ = pb::ByteString.Empty;
    /// <summary>
    /// The key being queried
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Key {
      get { return key_; }
      set {
        key_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "record" field.</summary>
    public const int RecordFieldNumber = 3;
    private global::Libp2p.Protocols.KadDht.Messages.Record record_;
    /// <summary>
    /// The record being sent (for PUT_VALUE)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Libp2p.Protocols.KadDht.Messages.Record Record {
      get { return record_; }
      set {
        record_ = value;
      }
    }

    /// <summary>Field number for the "closerPeers" field.</summary>
    public const int CloserPeersFieldNumber = 8;
    private static readonly pb::FieldCodec<global::Libp2p.Protocols.KadDht.Messages.Peer> _repeated_closerPeers_codec
        = pb::FieldCodec.ForMessage(66, global::Libp2p.Protocols.KadDht.Messages.Peer.Parser);
    private readonly pbc::RepeatedField<global::Libp2p.Protocols.KadDht.Messages.Peer> closerPeers_ = new pbc::RepeatedField<global::Libp2p.Protocols.KadDht.Messages.Peer>();
    /// <summary>
    /// A set of peer addresses (for responses)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Libp2p.Protocols.KadDht.Messages.Peer> CloserPeers {
      get { return closerPeers_; }
    }

    /// <summary>Field number for the "providerPeers" field.</summary>
    public const int ProviderPeersFieldNumber = 9;
    private static readonly pb::FieldCodec<global::Libp2p.Protocols.KadDht.Messages.Peer> _repeated_providerPeers_codec
        = pb::FieldCodec.ForMessage(74, global::Libp2p.Protocols.KadDht.Messages.Peer.Parser);
    private readonly pbc::RepeatedField<global::Libp2p.Protocols.KadDht.Messages.Peer> providerPeers_ = new pbc::RepeatedField<global::Libp2p.Protocols.KadDht.Messages.Peer>();
    /// <summary>
    /// Provider records (for ADD_PROVIDER/GET_PROVIDERS)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Libp2p.Protocols.KadDht.Messages.Peer> ProviderPeers {
      get { return providerPeers_; }
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 6;
    private pb::ByteString value_ = pb::ByteString.Empty;
    /// <summary>
    /// Optional value for direct response
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Value {
      get { return value_; }
      set {
        value_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "clusterLevel" field.</summary>
    public const int ClusterLevelFieldNumber = 7;
    private int clusterLevel_;
    /// <summary>
    /// Cluster level for the query
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ClusterLevel {
      get { return clusterLevel_; }
      set {
        clusterLevel_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Message);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Message other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (Key != other.Key) return false;
      if (!object.Equals(Record, other.Record)) return false;
      if(!closerPeers_.Equals(other.closerPeers_)) return false;
      if(!providerPeers_.Equals(other.providerPeers_)) return false;
      if (Value != other.Value) return false;
      if (ClusterLevel != other.ClusterLevel) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Libp2p.Protocols.KadDht.Messages.MessageType.PutValue) hash ^= Type.GetHashCode();
      if (Key.Length != 0) hash ^= Key.GetHashCode();
      if (record_ != null) hash ^= Record.GetHashCode();
      hash ^= closerPeers_.GetHashCode();
      hash ^= providerPeers_.GetHashCode();
      if (Value.Length != 0) hash ^= Value.GetHashCode();
      if (ClusterLevel != 0) hash ^= ClusterLevel.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Libp2p.Protocols.KadDht.Messages.MessageType.PutValue) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Key.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Key);
      }
      if (record_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Record);
      }
      if (Value.Length != 0) {
        output.WriteRawTag(50);
        output.WriteBytes(Value);
      }
      if (ClusterLevel != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(ClusterLevel);
      }
      closerPeers_.WriteTo(output, _repeated_closerPeers_codec);
      providerPeers_.WriteTo(output, _repeated_providerPeers_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Libp2p.Protocols.KadDht.Messages.MessageType.PutValue) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Key.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Key);
      }
      if (record_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Record);
      }
      if (Value.Length != 0) {
        output.WriteRawTag(50);
        output.WriteBytes(Value);
      }
      if (ClusterLevel != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(ClusterLevel);
      }
      closerPeers_.WriteTo(ref output, _repeated_closerPeers_codec);
      providerPeers_.WriteTo(ref output, _repeated_providerPeers_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Libp2p.Protocols.KadDht.Messages.MessageType.PutValue) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Key.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Key);
      }
      if (record_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Record);
      }
      size += closerPeers_.CalculateSize(_repeated_closerPeers_codec);
      size += providerPeers_.CalculateSize(_repeated_providerPeers_codec);
      if (Value.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Value);
      }
      if (ClusterLevel != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ClusterLevel);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Message other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Libp2p.Protocols.KadDht.Messages.MessageType.PutValue) {
        Type = other.Type;
      }
      if (other.Key.Length != 0) {
        Key = other.Key;
      }
      if (other.record_ != null) {
        if (record_ == null) {
          Record = new global::Libp2p.Protocols.KadDht.Messages.Record();
        }
        Record.MergeFrom(other.Record);
      }
      closerPeers_.Add(other.closerPeers_);
      providerPeers_.Add(other.providerPeers_);
      if (other.Value.Length != 0) {
        Value = other.Value;
      }
      if (other.ClusterLevel != 0) {
        ClusterLevel = other.ClusterLevel;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Libp2p.Protocols.KadDht.Messages.MessageType) input.ReadEnum();
            break;
          }
          case 18: {
            Key = input.ReadBytes();
            break;
          }
          case 26: {
            if (record_ == null) {
              Record = new global::Libp2p.Protocols.KadDht.Messages.Record();
            }
            input.ReadMessage(Record);
            break;
          }
          case 50: {
            Value = input.ReadBytes();
            break;
          }
          case 56: {
            ClusterLevel = input.ReadInt32();
            break;
          }
          case 66: {
            closerPeers_.AddEntriesFrom(input, _repeated_closerPeers_codec);
            break;
          }
          case 74: {
            providerPeers_.AddEntriesFrom(input, _repeated_providerPeers_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Libp2p.Protocols.KadDht.Messages.MessageType) input.ReadEnum();
            break;
          }
          case 18: {
            Key = input.ReadBytes();
            break;
          }
          case 26: {
            if (record_ == null) {
              Record = new global::Libp2p.Protocols.KadDht.Messages.Record();
            }
            input.ReadMessage(Record);
            break;
          }
          case 50: {
            Value = input.ReadBytes();
            break;
          }
          case 56: {
            ClusterLevel = input.ReadInt32();
            break;
          }
          case 66: {
            closerPeers_.AddEntriesFrom(ref input, _repeated_closerPeers_codec);
            break;
          }
          case 74: {
            providerPeers_.AddEntriesFrom(ref input, _repeated_providerPeers_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// ProviderRecord represents a provider of a value
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ProviderRecord : pb::IMessage<ProviderRecord>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProviderRecord> _parser = new pb::MessageParser<ProviderRecord>(() => new ProviderRecord());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProviderRecord> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Libp2p.Protocols.KadDht.Messages.KadDhtMessageReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProviderRecord() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProviderRecord(ProviderRecord other) : this() {
      key_ = other.key_;
      providerId_ = other.providerId_;
      timeReceived_ = other.timeReceived_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProviderRecord Clone() {
      return new ProviderRecord(this);
    }

    /// <summary>Field number for the "key" field.</summary>
    public const int KeyFieldNumber = 1;
    private pb::ByteString key_ = pb::ByteString.Empty;
    /// <summary>
    /// The key this peer is providing
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Key {
      get { return key_; }
      set {
        key_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "providerId" field.</summary>
    public const int ProviderIdFieldNumber = 2;
    private pb::ByteString providerId_ = pb::ByteString.Empty;
    /// <summary>
    /// The peer ID of the provider
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString ProviderId {
      get { return providerId_; }
      set {
        providerId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "timeReceived" field.</summary>
    public const int TimeReceivedFieldNumber = 3;
    private long timeReceived_;
    /// <summary>
    /// Time the provider record was received
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TimeReceived {
      get { return timeReceived_; }
      set {
        timeReceived_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProviderRecord);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProviderRecord other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Key != other.Key) return false;
      if (ProviderId != other.ProviderId) return false;
      if (TimeReceived != other.TimeReceived) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Key.Length != 0) hash ^= Key.GetHashCode();
      if (ProviderId.Length != 0) hash ^= ProviderId.GetHashCode();
      if (TimeReceived != 0L) hash ^= TimeReceived.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Key.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Key);
      }
      if (ProviderId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(ProviderId);
      }
      if (TimeReceived != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(TimeReceived);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Key.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Key);
      }
      if (ProviderId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(ProviderId);
      }
      if (TimeReceived != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(TimeReceived);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Key.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Key);
      }
      if (ProviderId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(ProviderId);
      }
      if (TimeReceived != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TimeReceived);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProviderRecord other) {
      if (other == null) {
        return;
      }
      if (other.Key.Length != 0) {
        Key = other.Key;
      }
      if (other.ProviderId.Length != 0) {
        ProviderId = other.ProviderId;
      }
      if (other.TimeReceived != 0L) {
        TimeReceived = other.TimeReceived;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Key = input.ReadBytes();
            break;
          }
          case 18: {
            ProviderId = input.ReadBytes();
            break;
          }
          case 24: {
            TimeReceived = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Key = input.ReadBytes();
            break;
          }
          case 18: {
            ProviderId = input.ReadBytes();
            break;
          }
          case 24: {
            TimeReceived = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Peer : pb::IMessage<Peer>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Peer> _parser = new pb::MessageParser<Peer>(() => new Peer());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Peer> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Libp2p.Protocols.KadDht.Messages.KadDhtMessageReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Peer() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Peer(Peer other) : this() {
      _hasBits0 = other._hasBits0;
      id_ = other.id_;
      addrs_ = other.addrs_.Clone();
      connection_ = other.connection_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Peer Clone() {
      return new Peer(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private pb::ByteString id_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "addrs" field.</summary>
    public const int AddrsFieldNumber = 2;
    private static readonly pb::FieldCodec<pb::ByteString> _repeated_addrs_codec
        = pb::FieldCodec.ForBytes(18);
    private readonly pbc::RepeatedField<pb::ByteString> addrs_ = new pbc::RepeatedField<pb::ByteString>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<pb::ByteString> Addrs {
      get { return addrs_; }
    }

    /// <summary>Field number for the "connection" field.</summary>
    public const int ConnectionFieldNumber = 3;
    private readonly static long ConnectionDefaultValue = 0L;

    private long connection_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Connection {
      get { if ((_hasBits0 & 1) != 0) { return connection_; } else { return ConnectionDefaultValue; } }
      set {
        _hasBits0 |= 1;
        connection_ = value;
      }
    }
    /// <summary>Gets whether the "connection" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasConnection {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "connection" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearConnection() {
      _hasBits0 &= ~1;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Peer);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Peer other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if(!addrs_.Equals(other.addrs_)) return false;
      if (Connection != other.Connection) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      hash ^= addrs_.GetHashCode();
      if (HasConnection) hash ^= Connection.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Id);
      }
      addrs_.WriteTo(output, _repeated_addrs_codec);
      if (HasConnection) {
        output.WriteRawTag(24);
        output.WriteInt64(Connection);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Id);
      }
      addrs_.WriteTo(ref output, _repeated_addrs_codec);
      if (HasConnection) {
        output.WriteRawTag(24);
        output.WriteInt64(Connection);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Id);
      }
      size += addrs_.CalculateSize(_repeated_addrs_codec);
      if (HasConnection) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Connection);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Peer other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      addrs_.Add(other.addrs_);
      if (other.HasConnection) {
        Connection = other.Connection;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadBytes();
            break;
          }
          case 18: {
            addrs_.AddEntriesFrom(input, _repeated_addrs_codec);
            break;
          }
          case 24: {
            Connection = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadBytes();
            break;
          }
          case 18: {
            addrs_.AddEntriesFrom(ref input, _repeated_addrs_codec);
            break;
          }
          case 24: {
            Connection = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
