// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: IpnsEntry.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Nethermind.Libp2P.Protocols.KadDht.Dto {

  /// <summary>Holder for reflection information generated from IpnsEntry.proto</summary>
  public static partial class IpnsEntryReflection {

    #region Descriptor
    /// <summary>File descriptor for IpnsEntry.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static IpnsEntryReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9JcG5zRW50cnkucHJvdG8SJk5ldGhlcm1pbmQuTGlicDJwLlByb3RvY29s",
            "cy5LYWREaHQuRHRvIoICCglJcG5zRW50cnkSDQoFdmFsdWUYASABKAwSEwoL",
            "c2lnbmF0dXJlVjEYAiABKAwSVAoMdmFsaWRpdHlUeXBlGAMgASgOMj4uTmV0",
            "aGVybWluZC5MaWJwMnAuUHJvdG9jb2xzLkthZERodC5EdG8uSXBuc0VudHJ5",
            "LlZhbGlkaXR5VHlwZRIQCgh2YWxpZGl0eRgEIAEoDBIQCghzZXF1ZW5jZRgF",
            "IAEoBBILCgN0dGwYBiABKAQSDgoGcHViS2V5GAcgASgMEhMKC3NpZ25hdHVy",
            "ZVYyGAggASgMEgwKBGRhdGEYCSABKAwiFwoMVmFsaWRpdHlUeXBlEgcKA0VP",
            "TBAA"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Nethermind.Libp2P.Protocols.KadDht.Dto.IpnsEntry), global::Nethermind.Libp2P.Protocols.KadDht.Dto.IpnsEntry.Parser, new[]{ "Value", "SignatureV1", "ValidityType", "Validity", "Sequence", "Ttl", "PubKey", "SignatureV2", "Data" }, null, new[]{ typeof(global::Nethermind.Libp2P.Protocols.KadDht.Dto.IpnsEntry.Types.ValidityType) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// IpnsEntry per https://specs.ipfs.tech/ipns/ipns-record/
  /// Compatible with go-libp2p, js-libp2p, rust-libp2p
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class IpnsEntry : pb::IMessage<IpnsEntry>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<IpnsEntry> _parser = new pb::MessageParser<IpnsEntry>(() => new IpnsEntry());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<IpnsEntry> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Nethermind.Libp2P.Protocols.KadDht.Dto.IpnsEntryReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IpnsEntry() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IpnsEntry(IpnsEntry other) : this() {
      _hasBits0 = other._hasBits0;
      value_ = other.value_;
      signatureV1_ = other.signatureV1_;
      validityType_ = other.validityType_;
      validity_ = other.validity_;
      sequence_ = other.sequence_;
      ttl_ = other.ttl_;
      pubKey_ = other.pubKey_;
      signatureV2_ = other.signatureV2_;
      data_ = other.data_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IpnsEntry Clone() {
      return new IpnsEntry(this);
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 1;
    private readonly static pb::ByteString ValueDefaultValue = pb::ByteString.Empty;

    private pb::ByteString value_;
    /// <summary>
    /// value is the value this record is storing (e.g., /ipfs/Qm... path)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Value {
      get { return value_ ?? ValueDefaultValue; }
      set {
        value_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "value" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasValue {
      get { return value_ != null; }
    }
    /// <summary>Clears the value of the "value" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearValue() {
      value_ = null;
    }

    /// <summary>Field number for the "signatureV1" field.</summary>
    public const int SignatureV1FieldNumber = 2;
    private readonly static pb::ByteString SignatureV1DefaultValue = pb::ByteString.Empty;

    private pb::ByteString signatureV1_;
    /// <summary>
    /// signatureV1 is a legacy RSA signature (deprecated in v2, kept for backward compat)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString SignatureV1 {
      get { return signatureV1_ ?? SignatureV1DefaultValue; }
      set {
        signatureV1_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "signatureV1" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasSignatureV1 {
      get { return signatureV1_ != null; }
    }
    /// <summary>Clears the value of the "signatureV1" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearSignatureV1() {
      signatureV1_ = null;
    }

    /// <summary>Field number for the "validityType" field.</summary>
    public const int ValidityTypeFieldNumber = 3;
    private readonly static global::Nethermind.Libp2P.Protocols.KadDht.Dto.IpnsEntry.Types.ValidityType ValidityTypeDefaultValue = global::Nethermind.Libp2P.Protocols.KadDht.Dto.IpnsEntry.Types.ValidityType.Eol;

    private global::Nethermind.Libp2P.Protocols.KadDht.Dto.IpnsEntry.Types.ValidityType validityType_;
    /// <summary>
    /// validityType specifies the type of validity check (currently only EOL)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Nethermind.Libp2P.Protocols.KadDht.Dto.IpnsEntry.Types.ValidityType ValidityType {
      get { if ((_hasBits0 & 1) != 0) { return validityType_; } else { return ValidityTypeDefaultValue; } }
      set {
        _hasBits0 |= 1;
        validityType_ = value;
      }
    }
    /// <summary>Gets whether the "validityType" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasValidityType {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "validityType" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearValidityType() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "validity" field.</summary>
    public const int ValidityFieldNumber = 4;
    private readonly static pb::ByteString ValidityDefaultValue = pb::ByteString.Empty;

    private pb::ByteString validity_;
    /// <summary>
    /// validity contains the data for the validity type (RFC 3339 datetime for EOL)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Validity {
      get { return validity_ ?? ValidityDefaultValue; }
      set {
        validity_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "validity" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasValidity {
      get { return validity_ != null; }
    }
    /// <summary>Clears the value of the "validity" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearValidity() {
      validity_ = null;
    }

    /// <summary>Field number for the "sequence" field.</summary>
    public const int SequenceFieldNumber = 5;
    private readonly static ulong SequenceDefaultValue = 0UL;

    private ulong sequence_;
    /// <summary>
    /// sequence is a monotonically increasing counter for ordering records
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Sequence {
      get { if ((_hasBits0 & 2) != 0) { return sequence_; } else { return SequenceDefaultValue; } }
      set {
        _hasBits0 |= 2;
        sequence_ = value;
      }
    }
    /// <summary>Gets whether the "sequence" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasSequence {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "sequence" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearSequence() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "ttl" field.</summary>
    public const int TtlFieldNumber = 6;
    private readonly static ulong TtlDefaultValue = 0UL;

    private ulong ttl_;
    /// <summary>
    /// ttl is a hint for how long the record should be cached (nanoseconds)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Ttl {
      get { if ((_hasBits0 & 4) != 0) { return ttl_; } else { return TtlDefaultValue; } }
      set {
        _hasBits0 |= 4;
        ttl_ = value;
      }
    }
    /// <summary>Gets whether the "ttl" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasTtl {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "ttl" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearTtl() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "pubKey" field.</summary>
    public const int PubKeyFieldNumber = 7;
    private readonly static pb::ByteString PubKeyDefaultValue = pb::ByteString.Empty;

    private pb::ByteString pubKey_;
    /// <summary>
    /// pubKey is the public key of the author (may be omitted if extractable from IPNS key)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString PubKey {
      get { return pubKey_ ?? PubKeyDefaultValue; }
      set {
        pubKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "pubKey" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPubKey {
      get { return pubKey_ != null; }
    }
    /// <summary>Clears the value of the "pubKey" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPubKey() {
      pubKey_ = null;
    }

    /// <summary>Field number for the "signatureV2" field.</summary>
    public const int SignatureV2FieldNumber = 8;
    private readonly static pb::ByteString SignatureV2DefaultValue = pb::ByteString.Empty;

    private pb::ByteString signatureV2_;
    /// <summary>
    /// signatureV2 is the v2 signature over the CBOR-encoded "data" field
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString SignatureV2 {
      get { return signatureV2_ ?? SignatureV2DefaultValue; }
      set {
        signatureV2_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "signatureV2" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasSignatureV2 {
      get { return signatureV2_ != null; }
    }
    /// <summary>Clears the value of the "signatureV2" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearSignatureV2() {
      signatureV2_ = null;
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 9;
    private readonly static pb::ByteString DataDefaultValue = pb::ByteString.Empty;

    private pb::ByteString data_;
    /// <summary>
    /// data is the CBOR-encoded payload: { Value, Validity, ValidityType, Sequence, TTL }
    /// Used for v2 signature verification
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Data {
      get { return data_ ?? DataDefaultValue; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "data" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasData {
      get { return data_ != null; }
    }
    /// <summary>Clears the value of the "data" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearData() {
      data_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as IpnsEntry);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(IpnsEntry other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Value != other.Value) return false;
      if (SignatureV1 != other.SignatureV1) return false;
      if (ValidityType != other.ValidityType) return false;
      if (Validity != other.Validity) return false;
      if (Sequence != other.Sequence) return false;
      if (Ttl != other.Ttl) return false;
      if (PubKey != other.PubKey) return false;
      if (SignatureV2 != other.SignatureV2) return false;
      if (Data != other.Data) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasValue) hash ^= Value.GetHashCode();
      if (HasSignatureV1) hash ^= SignatureV1.GetHashCode();
      if (HasValidityType) hash ^= ValidityType.GetHashCode();
      if (HasValidity) hash ^= Validity.GetHashCode();
      if (HasSequence) hash ^= Sequence.GetHashCode();
      if (HasTtl) hash ^= Ttl.GetHashCode();
      if (HasPubKey) hash ^= PubKey.GetHashCode();
      if (HasSignatureV2) hash ^= SignatureV2.GetHashCode();
      if (HasData) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasValue) {
        output.WriteRawTag(10);
        output.WriteBytes(Value);
      }
      if (HasSignatureV1) {
        output.WriteRawTag(18);
        output.WriteBytes(SignatureV1);
      }
      if (HasValidityType) {
        output.WriteRawTag(24);
        output.WriteEnum((int) ValidityType);
      }
      if (HasValidity) {
        output.WriteRawTag(34);
        output.WriteBytes(Validity);
      }
      if (HasSequence) {
        output.WriteRawTag(40);
        output.WriteUInt64(Sequence);
      }
      if (HasTtl) {
        output.WriteRawTag(48);
        output.WriteUInt64(Ttl);
      }
      if (HasPubKey) {
        output.WriteRawTag(58);
        output.WriteBytes(PubKey);
      }
      if (HasSignatureV2) {
        output.WriteRawTag(66);
        output.WriteBytes(SignatureV2);
      }
      if (HasData) {
        output.WriteRawTag(74);
        output.WriteBytes(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasValue) {
        output.WriteRawTag(10);
        output.WriteBytes(Value);
      }
      if (HasSignatureV1) {
        output.WriteRawTag(18);
        output.WriteBytes(SignatureV1);
      }
      if (HasValidityType) {
        output.WriteRawTag(24);
        output.WriteEnum((int) ValidityType);
      }
      if (HasValidity) {
        output.WriteRawTag(34);
        output.WriteBytes(Validity);
      }
      if (HasSequence) {
        output.WriteRawTag(40);
        output.WriteUInt64(Sequence);
      }
      if (HasTtl) {
        output.WriteRawTag(48);
        output.WriteUInt64(Ttl);
      }
      if (HasPubKey) {
        output.WriteRawTag(58);
        output.WriteBytes(PubKey);
      }
      if (HasSignatureV2) {
        output.WriteRawTag(66);
        output.WriteBytes(SignatureV2);
      }
      if (HasData) {
        output.WriteRawTag(74);
        output.WriteBytes(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasValue) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Value);
      }
      if (HasSignatureV1) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(SignatureV1);
      }
      if (HasValidityType) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ValidityType);
      }
      if (HasValidity) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Validity);
      }
      if (HasSequence) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Sequence);
      }
      if (HasTtl) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Ttl);
      }
      if (HasPubKey) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(PubKey);
      }
      if (HasSignatureV2) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(SignatureV2);
      }
      if (HasData) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(IpnsEntry other) {
      if (other == null) {
        return;
      }
      if (other.HasValue) {
        Value = other.Value;
      }
      if (other.HasSignatureV1) {
        SignatureV1 = other.SignatureV1;
      }
      if (other.HasValidityType) {
        ValidityType = other.ValidityType;
      }
      if (other.HasValidity) {
        Validity = other.Validity;
      }
      if (other.HasSequence) {
        Sequence = other.Sequence;
      }
      if (other.HasTtl) {
        Ttl = other.Ttl;
      }
      if (other.HasPubKey) {
        PubKey = other.PubKey;
      }
      if (other.HasSignatureV2) {
        SignatureV2 = other.SignatureV2;
      }
      if (other.HasData) {
        Data = other.Data;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Value = input.ReadBytes();
            break;
          }
          case 18: {
            SignatureV1 = input.ReadBytes();
            break;
          }
          case 24: {
            ValidityType = (global::Nethermind.Libp2P.Protocols.KadDht.Dto.IpnsEntry.Types.ValidityType) input.ReadEnum();
            break;
          }
          case 34: {
            Validity = input.ReadBytes();
            break;
          }
          case 40: {
            Sequence = input.ReadUInt64();
            break;
          }
          case 48: {
            Ttl = input.ReadUInt64();
            break;
          }
          case 58: {
            PubKey = input.ReadBytes();
            break;
          }
          case 66: {
            SignatureV2 = input.ReadBytes();
            break;
          }
          case 74: {
            Data = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Value = input.ReadBytes();
            break;
          }
          case 18: {
            SignatureV1 = input.ReadBytes();
            break;
          }
          case 24: {
            ValidityType = (global::Nethermind.Libp2P.Protocols.KadDht.Dto.IpnsEntry.Types.ValidityType) input.ReadEnum();
            break;
          }
          case 34: {
            Validity = input.ReadBytes();
            break;
          }
          case 40: {
            Sequence = input.ReadUInt64();
            break;
          }
          case 48: {
            Ttl = input.ReadUInt64();
            break;
          }
          case 58: {
            PubKey = input.ReadBytes();
            break;
          }
          case 66: {
            SignatureV2 = input.ReadBytes();
            break;
          }
          case 74: {
            Data = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the IpnsEntry message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum ValidityType {
        /// <summary>
        /// Setting an EOL says "this record is valid until..."
        /// </summary>
        [pbr::OriginalName("EOL")] Eol = 0,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
