language: csharp
sudo: required
dist: trusty
env:
  - CLI_VERSION=latest

addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
mono:
  - latest
os:
  - linux
  - osx

notifications:
  email:
    on_success: change
    on_failure: always

branches:
  only:
    - master

cache:
  bundler: true
  directories:
  - ./packages
  - /.dotnetcli
  - $HOME/Library/Caches/Homebrew

before_install:
  - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install openssl; ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/; ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/; fi

install:
  - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
  - export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - export DOTNET_CLI_TELEMETRY_OPTOUT=1
  - curl -sSL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.1/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version "$CLI_VERSION" --install-dir "$DOTNET_INSTALL_DIR"
  - git config --global core.autocrlf input
  - chmod +x ./build.sh
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"

script:
  - ./build.sh
