// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Kademlia.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Nethermind.Libp2P.Protocols.KadDht.Dto {

  /// <summary>Holder for reflection information generated from Kademlia.proto</summary>
  public static partial class KademliaReflection {

    #region Descriptor
    /// <summary>File descriptor for Kademlia.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static KademliaReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5LYWRlbWxpYS5wcm90bxImTmV0aGVybWluZC5MaWJwMnAuUHJvdG9jb2xz",
            "LkthZERodC5EdG8iOgoGUmVjb3JkEgsKA2tleRgBIAEoDBINCgV2YWx1ZRgC",
            "IAEoDBIUCgx0aW1lUmVjZWl2ZWQYBSABKAkijQUKB01lc3NhZ2USSQoEdHlw",
            "ZRgBIAEoDjI7Lk5ldGhlcm1pbmQuTGlicDJwLlByb3RvY29scy5LYWREaHQu",
            "RHRvLk1lc3NhZ2UuTWVzc2FnZVR5cGUSFwoPY2x1c3RlckxldmVsUmF3GAog",
            "ASgFEgsKA2tleRgCIAEoDBI+CgZyZWNvcmQYAyABKAsyLi5OZXRoZXJtaW5k",
            "LkxpYnAycC5Qcm90b2NvbHMuS2FkRGh0LkR0by5SZWNvcmQSSQoLY2xvc2Vy",
            "UGVlcnMYCCADKAsyNC5OZXRoZXJtaW5kLkxpYnAycC5Qcm90b2NvbHMuS2Fk",
            "RGh0LkR0by5NZXNzYWdlLlBlZXISSwoNcHJvdmlkZXJQZWVycxgJIAMoCzI0",
            "Lk5ldGhlcm1pbmQuTGlicDJwLlByb3RvY29scy5LYWREaHQuRHRvLk1lc3Nh",
            "Z2UuUGVlchp1CgRQZWVyEgoKAmlkGAEgASgMEg0KBWFkZHJzGAIgAygMElIK",
            "CmNvbm5lY3Rpb24YAyABKA4yPi5OZXRoZXJtaW5kLkxpYnAycC5Qcm90b2Nv",
            "bHMuS2FkRGh0LkR0by5NZXNzYWdlLkNvbm5lY3Rpb25UeXBlImkKC01lc3Nh",
            "Z2VUeXBlEg0KCVBVVF9WQUxVRRAAEg0KCUdFVF9WQUxVRRABEhAKDEFERF9Q",
            "Uk9WSURFUhACEhEKDUdFVF9QUk9WSURFUlMQAxINCglGSU5EX05PREUQBBII",
            "CgRQSU5HEAUiVwoOQ29ubmVjdGlvblR5cGUSEQoNTk9UX0NPTk5FQ1RFRBAA",
            "Eg0KCUNPTk5FQ1RFRBABEg8KC0NBTl9DT05ORUNUEAISEgoOQ0FOTk9UX0NP",
            "Tk5FQ1QQAw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Nethermind.Libp2P.Protocols.KadDht.Dto.Record), global::Nethermind.Libp2P.Protocols.KadDht.Dto.Record.Parser, new[]{ "Key", "Value", "TimeReceived" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Nethermind.Libp2P.Protocols.KadDht.Dto.Message), global::Nethermind.Libp2P.Protocols.KadDht.Dto.Message.Parser, new[]{ "Type", "ClusterLevelRaw", "Key", "Record", "CloserPeers", "ProviderPeers" }, null, new[]{ typeof(global::Nethermind.Libp2P.Protocols.KadDht.Dto.Message.Types.MessageType), typeof(global::Nethermind.Libp2P.Protocols.KadDht.Dto.Message.Types.ConnectionType) }, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Nethermind.Libp2P.Protocols.KadDht.Dto.Message.Types.Peer), global::Nethermind.Libp2P.Protocols.KadDht.Dto.Message.Types.Peer.Parser, new[]{ "Id", "Addrs", "Connection" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Record represents a dht record that contains a value for a key value pair
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Record : pb::IMessage<Record>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Record> _parser = new pb::MessageParser<Record>(() => new Record());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Record> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Nethermind.Libp2P.Protocols.KadDht.Dto.KademliaReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Record() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Record(Record other) : this() {
      key_ = other.key_;
      value_ = other.value_;
      timeReceived_ = other.timeReceived_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Record Clone() {
      return new Record(this);
    }

    /// <summary>Field number for the "key" field.</summary>
    public const int KeyFieldNumber = 1;
    private readonly static pb::ByteString KeyDefaultValue = pb::ByteString.Empty;

    private pb::ByteString key_;
    /// <summary>
    /// The key that references this record
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Key {
      get { return key_ ?? KeyDefaultValue; }
      set {
        key_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "key" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasKey {
      get { return key_ != null; }
    }
    /// <summary>Clears the value of the "key" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearKey() {
      key_ = null;
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 2;
    private readonly static pb::ByteString ValueDefaultValue = pb::ByteString.Empty;

    private pb::ByteString value_;
    /// <summary>
    /// The actual value this record is storing
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Value {
      get { return value_ ?? ValueDefaultValue; }
      set {
        value_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "value" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasValue {
      get { return value_ != null; }
    }
    /// <summary>Clears the value of the "value" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearValue() {
      value_ = null;
    }

    /// <summary>Field number for the "timeReceived" field.</summary>
    public const int TimeReceivedFieldNumber = 5;
    private readonly static string TimeReceivedDefaultValue = "";

    private string timeReceived_;
    /// <summary>
    /// Time the record was received, set by receiver
    /// Formatted according to https://datatracker.ietf.org/doc/html/rfc3339
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TimeReceived {
      get { return timeReceived_ ?? TimeReceivedDefaultValue; }
      set {
        timeReceived_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "timeReceived" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasTimeReceived {
      get { return timeReceived_ != null; }
    }
    /// <summary>Clears the value of the "timeReceived" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearTimeReceived() {
      timeReceived_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Record);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Record other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Key != other.Key) return false;
      if (Value != other.Value) return false;
      if (TimeReceived != other.TimeReceived) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasKey) hash ^= Key.GetHashCode();
      if (HasValue) hash ^= Value.GetHashCode();
      if (HasTimeReceived) hash ^= TimeReceived.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasKey) {
        output.WriteRawTag(10);
        output.WriteBytes(Key);
      }
      if (HasValue) {
        output.WriteRawTag(18);
        output.WriteBytes(Value);
      }
      if (HasTimeReceived) {
        output.WriteRawTag(42);
        output.WriteString(TimeReceived);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasKey) {
        output.WriteRawTag(10);
        output.WriteBytes(Key);
      }
      if (HasValue) {
        output.WriteRawTag(18);
        output.WriteBytes(Value);
      }
      if (HasTimeReceived) {
        output.WriteRawTag(42);
        output.WriteString(TimeReceived);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasKey) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Key);
      }
      if (HasValue) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Value);
      }
      if (HasTimeReceived) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TimeReceived);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Record other) {
      if (other == null) {
        return;
      }
      if (other.HasKey) {
        Key = other.Key;
      }
      if (other.HasValue) {
        Value = other.Value;
      }
      if (other.HasTimeReceived) {
        TimeReceived = other.TimeReceived;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Key = input.ReadBytes();
            break;
          }
          case 18: {
            Value = input.ReadBytes();
            break;
          }
          case 42: {
            TimeReceived = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Key = input.ReadBytes();
            break;
          }
          case 18: {
            Value = input.ReadBytes();
            break;
          }
          case 42: {
            TimeReceived = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Message : pb::IMessage<Message>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Message> _parser = new pb::MessageParser<Message>(() => new Message());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Message> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Nethermind.Libp2P.Protocols.KadDht.Dto.KademliaReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Message() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Message(Message other) : this() {
      _hasBits0 = other._hasBits0;
      type_ = other.type_;
      clusterLevelRaw_ = other.clusterLevelRaw_;
      key_ = other.key_;
      record_ = other.record_ != null ? other.record_.Clone() : null;
      closerPeers_ = other.closerPeers_.Clone();
      providerPeers_ = other.providerPeers_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Message Clone() {
      return new Message(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private readonly static global::Nethermind.Libp2P.Protocols.KadDht.Dto.Message.Types.MessageType TypeDefaultValue = global::Nethermind.Libp2P.Protocols.KadDht.Dto.Message.Types.MessageType.PutValue;

    private global::Nethermind.Libp2P.Protocols.KadDht.Dto.Message.Types.MessageType type_;
    /// <summary>
    /// defines what type of message it is.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Nethermind.Libp2P.Protocols.KadDht.Dto.Message.Types.MessageType Type {
      get { if ((_hasBits0 & 1) != 0) { return type_; } else { return TypeDefaultValue; } }
      set {
        _hasBits0 |= 1;
        type_ = value;
      }
    }
    /// <summary>Gets whether the "type" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasType {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "type" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearType() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "clusterLevelRaw" field.</summary>
    public const int ClusterLevelRawFieldNumber = 10;
    private readonly static int ClusterLevelRawDefaultValue = 0;

    private int clusterLevelRaw_;
    /// <summary>
    /// defines what coral cluster level this query/response belongs to.
    /// NOT USED
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ClusterLevelRaw {
      get { if ((_hasBits0 & 2) != 0) { return clusterLevelRaw_; } else { return ClusterLevelRawDefaultValue; } }
      set {
        _hasBits0 |= 2;
        clusterLevelRaw_ = value;
      }
    }
    /// <summary>Gets whether the "clusterLevelRaw" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasClusterLevelRaw {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "clusterLevelRaw" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearClusterLevelRaw() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "key" field.</summary>
    public const int KeyFieldNumber = 2;
    private readonly static pb::ByteString KeyDefaultValue = pb::ByteString.Empty;

    private pb::ByteString key_;
    /// <summary>
    /// Used to specify the key associated with this message.
    /// PUT_VALUE, GET_VALUE, ADD_PROVIDER, GET_PROVIDERS
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Key {
      get { return key_ ?? KeyDefaultValue; }
      set {
        key_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "key" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasKey {
      get { return key_ != null; }
    }
    /// <summary>Clears the value of the "key" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearKey() {
      key_ = null;
    }

    /// <summary>Field number for the "record" field.</summary>
    public const int RecordFieldNumber = 3;
    private global::Nethermind.Libp2P.Protocols.KadDht.Dto.Record record_;
    /// <summary>
    /// Used to return a value
    /// PUT_VALUE, GET_VALUE
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Nethermind.Libp2P.Protocols.KadDht.Dto.Record Record {
      get { return record_; }
      set {
        record_ = value;
      }
    }

    /// <summary>Field number for the "closerPeers" field.</summary>
    public const int CloserPeersFieldNumber = 8;
    private static readonly pb::FieldCodec<global::Nethermind.Libp2P.Protocols.KadDht.Dto.Message.Types.Peer> _repeated_closerPeers_codec
        = pb::FieldCodec.ForMessage(66, global::Nethermind.Libp2P.Protocols.KadDht.Dto.Message.Types.Peer.Parser);
    private readonly pbc::RepeatedField<global::Nethermind.Libp2P.Protocols.KadDht.Dto.Message.Types.Peer> closerPeers_ = new pbc::RepeatedField<global::Nethermind.Libp2P.Protocols.KadDht.Dto.Message.Types.Peer>();
    /// <summary>
    /// Used to return peers closer to a key in a query
    /// GET_VALUE, GET_PROVIDERS, FIND_NODE
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Nethermind.Libp2P.Protocols.KadDht.Dto.Message.Types.Peer> CloserPeers {
      get { return closerPeers_; }
    }

    /// <summary>Field number for the "providerPeers" field.</summary>
    public const int ProviderPeersFieldNumber = 9;
    private static readonly pb::FieldCodec<global::Nethermind.Libp2P.Protocols.KadDht.Dto.Message.Types.Peer> _repeated_providerPeers_codec
        = pb::FieldCodec.ForMessage(74, global::Nethermind.Libp2P.Protocols.KadDht.Dto.Message.Types.Peer.Parser);
    private readonly pbc::RepeatedField<global::Nethermind.Libp2P.Protocols.KadDht.Dto.Message.Types.Peer> providerPeers_ = new pbc::RepeatedField<global::Nethermind.Libp2P.Protocols.KadDht.Dto.Message.Types.Peer>();
    /// <summary>
    /// Used to return Providers
    /// GET_VALUE, ADD_PROVIDER, GET_PROVIDERS
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Nethermind.Libp2P.Protocols.KadDht.Dto.Message.Types.Peer> ProviderPeers {
      get { return providerPeers_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Message);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Message other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (ClusterLevelRaw != other.ClusterLevelRaw) return false;
      if (Key != other.Key) return false;
      if (!object.Equals(Record, other.Record)) return false;
      if(!closerPeers_.Equals(other.closerPeers_)) return false;
      if(!providerPeers_.Equals(other.providerPeers_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasType) hash ^= Type.GetHashCode();
      if (HasClusterLevelRaw) hash ^= ClusterLevelRaw.GetHashCode();
      if (HasKey) hash ^= Key.GetHashCode();
      if (record_ != null) hash ^= Record.GetHashCode();
      hash ^= closerPeers_.GetHashCode();
      hash ^= providerPeers_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasType) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (HasKey) {
        output.WriteRawTag(18);
        output.WriteBytes(Key);
      }
      if (record_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Record);
      }
      closerPeers_.WriteTo(output, _repeated_closerPeers_codec);
      providerPeers_.WriteTo(output, _repeated_providerPeers_codec);
      if (HasClusterLevelRaw) {
        output.WriteRawTag(80);
        output.WriteInt32(ClusterLevelRaw);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasType) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (HasKey) {
        output.WriteRawTag(18);
        output.WriteBytes(Key);
      }
      if (record_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Record);
      }
      closerPeers_.WriteTo(ref output, _repeated_closerPeers_codec);
      providerPeers_.WriteTo(ref output, _repeated_providerPeers_codec);
      if (HasClusterLevelRaw) {
        output.WriteRawTag(80);
        output.WriteInt32(ClusterLevelRaw);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasType) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (HasClusterLevelRaw) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ClusterLevelRaw);
      }
      if (HasKey) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Key);
      }
      if (record_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Record);
      }
      size += closerPeers_.CalculateSize(_repeated_closerPeers_codec);
      size += providerPeers_.CalculateSize(_repeated_providerPeers_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Message other) {
      if (other == null) {
        return;
      }
      if (other.HasType) {
        Type = other.Type;
      }
      if (other.HasClusterLevelRaw) {
        ClusterLevelRaw = other.ClusterLevelRaw;
      }
      if (other.HasKey) {
        Key = other.Key;
      }
      if (other.record_ != null) {
        if (record_ == null) {
          Record = new global::Nethermind.Libp2P.Protocols.KadDht.Dto.Record();
        }
        Record.MergeFrom(other.Record);
      }
      closerPeers_.Add(other.closerPeers_);
      providerPeers_.Add(other.providerPeers_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Nethermind.Libp2P.Protocols.KadDht.Dto.Message.Types.MessageType) input.ReadEnum();
            break;
          }
          case 18: {
            Key = input.ReadBytes();
            break;
          }
          case 26: {
            if (record_ == null) {
              Record = new global::Nethermind.Libp2P.Protocols.KadDht.Dto.Record();
            }
            input.ReadMessage(Record);
            break;
          }
          case 66: {
            closerPeers_.AddEntriesFrom(input, _repeated_closerPeers_codec);
            break;
          }
          case 74: {
            providerPeers_.AddEntriesFrom(input, _repeated_providerPeers_codec);
            break;
          }
          case 80: {
            ClusterLevelRaw = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Nethermind.Libp2P.Protocols.KadDht.Dto.Message.Types.MessageType) input.ReadEnum();
            break;
          }
          case 18: {
            Key = input.ReadBytes();
            break;
          }
          case 26: {
            if (record_ == null) {
              Record = new global::Nethermind.Libp2P.Protocols.KadDht.Dto.Record();
            }
            input.ReadMessage(Record);
            break;
          }
          case 66: {
            closerPeers_.AddEntriesFrom(ref input, _repeated_closerPeers_codec);
            break;
          }
          case 74: {
            providerPeers_.AddEntriesFrom(ref input, _repeated_providerPeers_codec);
            break;
          }
          case 80: {
            ClusterLevelRaw = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Message message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum MessageType {
        [pbr::OriginalName("PUT_VALUE")] PutValue = 0,
        [pbr::OriginalName("GET_VALUE")] GetValue = 1,
        [pbr::OriginalName("ADD_PROVIDER")] AddProvider = 2,
        [pbr::OriginalName("GET_PROVIDERS")] GetProviders = 3,
        [pbr::OriginalName("FIND_NODE")] FindNode = 4,
        [pbr::OriginalName("PING")] Ping = 5,
      }

      public enum ConnectionType {
        /// <summary>
        /// sender does not have a connection to peer, and no extra information (default)
        /// </summary>
        [pbr::OriginalName("NOT_CONNECTED")] NotConnected = 0,
        /// <summary>
        /// sender has a live connection to peer
        /// </summary>
        [pbr::OriginalName("CONNECTED")] Connected = 1,
        /// <summary>
        /// sender recently connected to peer
        /// </summary>
        [pbr::OriginalName("CAN_CONNECT")] CanConnect = 2,
        /// <summary>
        /// sender recently tried to connect to peer repeatedly but failed to connect
        /// </summary>
        [pbr::OriginalName("CANNOT_CONNECT")] CannotConnect = 3,
      }

      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class Peer : pb::IMessage<Peer>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Peer> _parser = new pb::MessageParser<Peer>(() => new Peer());
        private pb::UnknownFieldSet _unknownFields;
        private int _hasBits0;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Peer> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Nethermind.Libp2P.Protocols.KadDht.Dto.Message.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Peer() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Peer(Peer other) : this() {
          _hasBits0 = other._hasBits0;
          id_ = other.id_;
          addrs_ = other.addrs_.Clone();
          connection_ = other.connection_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Peer Clone() {
          return new Peer(this);
        }

        /// <summary>Field number for the "id" field.</summary>
        public const int IdFieldNumber = 1;
        private readonly static pb::ByteString IdDefaultValue = pb::ByteString.Empty;

        private pb::ByteString id_;
        /// <summary>
        /// ID of a given peer.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pb::ByteString Id {
          get { return id_ ?? IdDefaultValue; }
          set {
            id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }
        /// <summary>Gets whether the "id" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasId {
          get { return id_ != null; }
        }
        /// <summary>Clears the value of the "id" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearId() {
          id_ = null;
        }

        /// <summary>Field number for the "addrs" field.</summary>
        public const int AddrsFieldNumber = 2;
        private static readonly pb::FieldCodec<pb::ByteString> _repeated_addrs_codec
            = pb::FieldCodec.ForBytes(18);
        private readonly pbc::RepeatedField<pb::ByteString> addrs_ = new pbc::RepeatedField<pb::ByteString>();
        /// <summary>
        /// multiaddrs for a given peer
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::RepeatedField<pb::ByteString> Addrs {
          get { return addrs_; }
        }

        /// <summary>Field number for the "connection" field.</summary>
        public const int ConnectionFieldNumber = 3;
        private readonly static global::Nethermind.Libp2P.Protocols.KadDht.Dto.Message.Types.ConnectionType ConnectionDefaultValue = global::Nethermind.Libp2P.Protocols.KadDht.Dto.Message.Types.ConnectionType.NotConnected;

        private global::Nethermind.Libp2P.Protocols.KadDht.Dto.Message.Types.ConnectionType connection_;
        /// <summary>
        /// used to signal the sender's connection capabilities to the peer
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Nethermind.Libp2P.Protocols.KadDht.Dto.Message.Types.ConnectionType Connection {
          get { if ((_hasBits0 & 1) != 0) { return connection_; } else { return ConnectionDefaultValue; } }
          set {
            _hasBits0 |= 1;
            connection_ = value;
          }
        }
        /// <summary>Gets whether the "connection" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasConnection {
          get { return (_hasBits0 & 1) != 0; }
        }
        /// <summary>Clears the value of the "connection" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearConnection() {
          _hasBits0 &= ~1;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as Peer);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Peer other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Id != other.Id) return false;
          if(!addrs_.Equals(other.addrs_)) return false;
          if (Connection != other.Connection) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (HasId) hash ^= Id.GetHashCode();
          hash ^= addrs_.GetHashCode();
          if (HasConnection) hash ^= Connection.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (HasId) {
            output.WriteRawTag(10);
            output.WriteBytes(Id);
          }
          addrs_.WriteTo(output, _repeated_addrs_codec);
          if (HasConnection) {
            output.WriteRawTag(24);
            output.WriteEnum((int) Connection);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (HasId) {
            output.WriteRawTag(10);
            output.WriteBytes(Id);
          }
          addrs_.WriteTo(ref output, _repeated_addrs_codec);
          if (HasConnection) {
            output.WriteRawTag(24);
            output.WriteEnum((int) Connection);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (HasId) {
            size += 1 + pb::CodedOutputStream.ComputeBytesSize(Id);
          }
          size += addrs_.CalculateSize(_repeated_addrs_codec);
          if (HasConnection) {
            size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Connection);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Peer other) {
          if (other == null) {
            return;
          }
          if (other.HasId) {
            Id = other.Id;
          }
          addrs_.Add(other.addrs_);
          if (other.HasConnection) {
            Connection = other.Connection;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                Id = input.ReadBytes();
                break;
              }
              case 18: {
                addrs_.AddEntriesFrom(input, _repeated_addrs_codec);
                break;
              }
              case 24: {
                Connection = (global::Nethermind.Libp2P.Protocols.KadDht.Dto.Message.Types.ConnectionType) input.ReadEnum();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                Id = input.ReadBytes();
                break;
              }
              case 18: {
                addrs_.AddEntriesFrom(ref input, _repeated_addrs_codec);
                break;
              }
              case 24: {
                Connection = (global::Nethermind.Libp2P.Protocols.KadDht.Dto.Message.Types.ConnectionType) input.ReadEnum();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
